name: python-template

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync
      - name: Linting
        run: uv run flake8 src/ tests/
      - name: Type checking
        run: uv run mypy src/
      - name: Run tests
        run: uv run pytest tests/ --cov=src --cov-report=html --cov-report=term
