name: python-template

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync
      - name: linting
        run: uv run flake8 src/ tests/
      - name: type checking
        run: uv run mypy src/
      - name: Run tests
        run: uv run pytest tests/
